// <auto-generated />
namespace DLTD.Web.Main.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class createnewdb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(createnewdb));
        
        string IMigrationMetadata.Id
        {
            get { return "201611020420004_createnewdb"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
