// <auto-generated />
namespace DLTD.Web.Main.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class addtralaivb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addtralaivb));
        
        string IMigrationMetadata.Id
        {
            get { return "201608120318070_addtralaivb"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
