// <auto-generated />
namespace DLTD.Web.Main.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class ThemCotNgayHoanThanh : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ThemCotNgayHoanThanh));
        
        string IMigrationMetadata.Id
        {
            get { return "201604120023404_ThemCotNgayHoanThanh"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
