//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace QLVB.Core.WebServiceTruclienthongTinh {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Plugin_NSSGateway_NSSGatewayServiceSoapBinding", Namespace="urn:http.service.gateway.nss.com")]
    public partial class NSSGatewayServiceSoapService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback checkReceiverMessageOperationCompleted;
        
        private System.Threading.SendOrPostCallback getConnectionStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback getDownloadFileURLOperationCompleted;
        
        private System.Threading.SendOrPostCallback getMessageByMessageIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback getMessageIdsByPriorityOperationCompleted;
        
        private System.Threading.SendOrPostCallback getMessagePriorityByMessageIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback getMessagesOperationCompleted;
        
        private System.Threading.SendOrPostCallback getNumberOfReceiveMessageOperationCompleted;
        
        private System.Threading.SendOrPostCallback getOrgGatewayFromOrgInetOperationCompleted;
        
        private System.Threading.SendOrPostCallback getOrgInetFromOrgGatewayOperationCompleted;
        
        private System.Threading.SendOrPostCallback getOrganizationOperationCompleted;
        
        private System.Threading.SendOrPostCallback getOrganizationsOperationCompleted;
        
        private System.Threading.SendOrPostCallback getReceivedDocumentCodesOperationCompleted;
        
        private System.Threading.SendOrPostCallback getReceivedMessageIdsByDocumentTypeOperationCompleted;
        
        private System.Threading.SendOrPostCallback getReceivedMessageIdsByStartDateEndDateOperationCompleted;
        
        private System.Threading.SendOrPostCallback getReceivedMessageIdsOperationCompleted;
        
        private System.Threading.SendOrPostCallback getUploadFileURLOperationCompleted;
        
        private System.Threading.SendOrPostCallback hasReceiverMessageOperationCompleted;
        
        private System.Threading.SendOrPostCallback sendMessageOperationCompleted;
        
        private System.Threading.SendOrPostCallback synchronizationAllDepartmentGWOperationCompleted;
        
        private System.Threading.SendOrPostCallback synchronizationDepartmentByCodeOrganizationGWOperationCompleted;
        
        private System.Threading.SendOrPostCallback updateErrorMessageOperationCompleted;
        
        private System.Threading.SendOrPostCallback updateReceiveFinishOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public NSSGatewayServiceSoapService() {
            this.Url = global::QLVB.Core.Properties.Settings.Default.QLVB_Core_WebServiceTruclienthongTinh_NSSGatewayServiceSoapService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event checkReceiverMessageCompletedEventHandler checkReceiverMessageCompleted;
        
        /// <remarks/>
        public event getConnectionStatusCompletedEventHandler getConnectionStatusCompleted;
        
        /// <remarks/>
        public event getDownloadFileURLCompletedEventHandler getDownloadFileURLCompleted;
        
        /// <remarks/>
        public event getMessageByMessageIdCompletedEventHandler getMessageByMessageIdCompleted;
        
        /// <remarks/>
        public event getMessageIdsByPriorityCompletedEventHandler getMessageIdsByPriorityCompleted;
        
        /// <remarks/>
        public event getMessagePriorityByMessageIdCompletedEventHandler getMessagePriorityByMessageIdCompleted;
        
        /// <remarks/>
        public event getMessagesCompletedEventHandler getMessagesCompleted;
        
        /// <remarks/>
        public event getNumberOfReceiveMessageCompletedEventHandler getNumberOfReceiveMessageCompleted;
        
        /// <remarks/>
        public event getOrgGatewayFromOrgInetCompletedEventHandler getOrgGatewayFromOrgInetCompleted;
        
        /// <remarks/>
        public event getOrgInetFromOrgGatewayCompletedEventHandler getOrgInetFromOrgGatewayCompleted;
        
        /// <remarks/>
        public event getOrganizationCompletedEventHandler getOrganizationCompleted;
        
        /// <remarks/>
        public event getOrganizationsCompletedEventHandler getOrganizationsCompleted;
        
        /// <remarks/>
        public event getReceivedDocumentCodesCompletedEventHandler getReceivedDocumentCodesCompleted;
        
        /// <remarks/>
        public event getReceivedMessageIdsByDocumentTypeCompletedEventHandler getReceivedMessageIdsByDocumentTypeCompleted;
        
        /// <remarks/>
        public event getReceivedMessageIdsByStartDateEndDateCompletedEventHandler getReceivedMessageIdsByStartDateEndDateCompleted;
        
        /// <remarks/>
        public event getReceivedMessageIdsCompletedEventHandler getReceivedMessageIdsCompleted;
        
        /// <remarks/>
        public event getUploadFileURLCompletedEventHandler getUploadFileURLCompleted;
        
        /// <remarks/>
        public event hasReceiverMessageCompletedEventHandler hasReceiverMessageCompleted;
        
        /// <remarks/>
        public event sendMessageCompletedEventHandler sendMessageCompleted;
        
        /// <remarks/>
        public event synchronizationAllDepartmentGWCompletedEventHandler synchronizationAllDepartmentGWCompleted;
        
        /// <remarks/>
        public event synchronizationDepartmentByCodeOrganizationGWCompletedEventHandler synchronizationDepartmentByCodeOrganizationGWCompleted;
        
        /// <remarks/>
        public event updateErrorMessageCompletedEventHandler updateErrorMessageCompleted;
        
        /// <remarks/>
        public event updateReceiveFinishCompletedEventHandler updateReceiveFinishCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="urn:http.service.gateway.nss.com", ResponseNamespace="urn:http.service.gateway.nss.com")]
        [return: System.Xml.Serialization.SoapElementAttribute("checkReceiverMessageReturn")]
        public string checkReceiverMessage(long messageId, string receiverOrgId) {
            object[] results = this.Invoke("checkReceiverMessage", new object[] {
                        messageId,
                        receiverOrgId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void checkReceiverMessageAsync(long messageId, string receiverOrgId) {
            this.checkReceiverMessageAsync(messageId, receiverOrgId, null);
        }
        
        /// <remarks/>
        public void checkReceiverMessageAsync(long messageId, string receiverOrgId, object userState) {
            if ((this.checkReceiverMessageOperationCompleted == null)) {
                this.checkReceiverMessageOperationCompleted = new System.Threading.SendOrPostCallback(this.OncheckReceiverMessageOperationCompleted);
            }
            this.InvokeAsync("checkReceiverMessage", new object[] {
                        messageId,
                        receiverOrgId}, this.checkReceiverMessageOperationCompleted, userState);
        }
        
        private void OncheckReceiverMessageOperationCompleted(object arg) {
            if ((this.checkReceiverMessageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.checkReceiverMessageCompleted(this, new checkReceiverMessageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="urn:http.service.gateway.nss.com", ResponseNamespace="urn:http.service.gateway.nss.com")]
        [return: System.Xml.Serialization.SoapElementAttribute("getConnectionStatusReturn")]
        public int getConnectionStatus(string orgCode) {
            object[] results = this.Invoke("getConnectionStatus", new object[] {
                        orgCode});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void getConnectionStatusAsync(string orgCode) {
            this.getConnectionStatusAsync(orgCode, null);
        }
        
        /// <remarks/>
        public void getConnectionStatusAsync(string orgCode, object userState) {
            if ((this.getConnectionStatusOperationCompleted == null)) {
                this.getConnectionStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetConnectionStatusOperationCompleted);
            }
            this.InvokeAsync("getConnectionStatus", new object[] {
                        orgCode}, this.getConnectionStatusOperationCompleted, userState);
        }
        
        private void OngetConnectionStatusOperationCompleted(object arg) {
            if ((this.getConnectionStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getConnectionStatusCompleted(this, new getConnectionStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="urn:http.service.gateway.nss.com", ResponseNamespace="urn:http.service.gateway.nss.com")]
        [return: System.Xml.Serialization.SoapElementAttribute("getDownloadFileURLReturn")]
        public string getDownloadFileURL(string ipAddress, string fileId) {
            object[] results = this.Invoke("getDownloadFileURL", new object[] {
                        ipAddress,
                        fileId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getDownloadFileURLAsync(string ipAddress, string fileId) {
            this.getDownloadFileURLAsync(ipAddress, fileId, null);
        }
        
        /// <remarks/>
        public void getDownloadFileURLAsync(string ipAddress, string fileId, object userState) {
            if ((this.getDownloadFileURLOperationCompleted == null)) {
                this.getDownloadFileURLOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetDownloadFileURLOperationCompleted);
            }
            this.InvokeAsync("getDownloadFileURL", new object[] {
                        ipAddress,
                        fileId}, this.getDownloadFileURLOperationCompleted, userState);
        }
        
        private void OngetDownloadFileURLOperationCompleted(object arg) {
            if ((this.getDownloadFileURLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getDownloadFileURLCompleted(this, new getDownloadFileURLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="urn:http.service.gateway.nss.com", ResponseNamespace="urn:http.service.gateway.nss.com")]
        [return: System.Xml.Serialization.SoapElementAttribute("getMessageByMessageIdReturn")]
        public string getMessageByMessageId(string messageId) {
            object[] results = this.Invoke("getMessageByMessageId", new object[] {
                        messageId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getMessageByMessageIdAsync(string messageId) {
            this.getMessageByMessageIdAsync(messageId, null);
        }
        
        /// <remarks/>
        public void getMessageByMessageIdAsync(string messageId, object userState) {
            if ((this.getMessageByMessageIdOperationCompleted == null)) {
                this.getMessageByMessageIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetMessageByMessageIdOperationCompleted);
            }
            this.InvokeAsync("getMessageByMessageId", new object[] {
                        messageId}, this.getMessageByMessageIdOperationCompleted, userState);
        }
        
        private void OngetMessageByMessageIdOperationCompleted(object arg) {
            if ((this.getMessageByMessageIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getMessageByMessageIdCompleted(this, new getMessageByMessageIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="urn:http.service.gateway.nss.com", ResponseNamespace="urn:http.service.gateway.nss.com")]
        [return: System.Xml.Serialization.SoapElementAttribute("getMessageIdsByPriorityReturn")]
        public string getMessageIdsByPriority(string documentType, int offset) {
            object[] results = this.Invoke("getMessageIdsByPriority", new object[] {
                        documentType,
                        offset});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getMessageIdsByPriorityAsync(string documentType, int offset) {
            this.getMessageIdsByPriorityAsync(documentType, offset, null);
        }
        
        /// <remarks/>
        public void getMessageIdsByPriorityAsync(string documentType, int offset, object userState) {
            if ((this.getMessageIdsByPriorityOperationCompleted == null)) {
                this.getMessageIdsByPriorityOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetMessageIdsByPriorityOperationCompleted);
            }
            this.InvokeAsync("getMessageIdsByPriority", new object[] {
                        documentType,
                        offset}, this.getMessageIdsByPriorityOperationCompleted, userState);
        }
        
        private void OngetMessageIdsByPriorityOperationCompleted(object arg) {
            if ((this.getMessageIdsByPriorityCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getMessageIdsByPriorityCompleted(this, new getMessageIdsByPriorityCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="urn:http.service.gateway.nss.com", ResponseNamespace="urn:http.service.gateway.nss.com")]
        [return: System.Xml.Serialization.SoapElementAttribute("getMessagePriorityByMessageIdReturn")]
        public string getMessagePriorityByMessageId(long messageId) {
            object[] results = this.Invoke("getMessagePriorityByMessageId", new object[] {
                        messageId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getMessagePriorityByMessageIdAsync(long messageId) {
            this.getMessagePriorityByMessageIdAsync(messageId, null);
        }
        
        /// <remarks/>
        public void getMessagePriorityByMessageIdAsync(long messageId, object userState) {
            if ((this.getMessagePriorityByMessageIdOperationCompleted == null)) {
                this.getMessagePriorityByMessageIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetMessagePriorityByMessageIdOperationCompleted);
            }
            this.InvokeAsync("getMessagePriorityByMessageId", new object[] {
                        messageId}, this.getMessagePriorityByMessageIdOperationCompleted, userState);
        }
        
        private void OngetMessagePriorityByMessageIdOperationCompleted(object arg) {
            if ((this.getMessagePriorityByMessageIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getMessagePriorityByMessageIdCompleted(this, new getMessagePriorityByMessageIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="urn:http.service.gateway.nss.com", ResponseNamespace="urn:http.service.gateway.nss.com")]
        [return: System.Xml.Serialization.SoapElementAttribute("getMessagesReturn")]
        public string[] getMessages() {
            object[] results = this.Invoke("getMessages", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void getMessagesAsync() {
            this.getMessagesAsync(null);
        }
        
        /// <remarks/>
        public void getMessagesAsync(object userState) {
            if ((this.getMessagesOperationCompleted == null)) {
                this.getMessagesOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetMessagesOperationCompleted);
            }
            this.InvokeAsync("getMessages", new object[0], this.getMessagesOperationCompleted, userState);
        }
        
        private void OngetMessagesOperationCompleted(object arg) {
            if ((this.getMessagesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getMessagesCompleted(this, new getMessagesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="urn:http.service.gateway.nss.com", ResponseNamespace="urn:http.service.gateway.nss.com")]
        [return: System.Xml.Serialization.SoapElementAttribute("getNumberOfReceiveMessageReturn")]
        public int getNumberOfReceiveMessage() {
            object[] results = this.Invoke("getNumberOfReceiveMessage", new object[0]);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void getNumberOfReceiveMessageAsync() {
            this.getNumberOfReceiveMessageAsync(null);
        }
        
        /// <remarks/>
        public void getNumberOfReceiveMessageAsync(object userState) {
            if ((this.getNumberOfReceiveMessageOperationCompleted == null)) {
                this.getNumberOfReceiveMessageOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetNumberOfReceiveMessageOperationCompleted);
            }
            this.InvokeAsync("getNumberOfReceiveMessage", new object[0], this.getNumberOfReceiveMessageOperationCompleted, userState);
        }
        
        private void OngetNumberOfReceiveMessageOperationCompleted(object arg) {
            if ((this.getNumberOfReceiveMessageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getNumberOfReceiveMessageCompleted(this, new getNumberOfReceiveMessageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="urn:http.service.gateway.nss.com", ResponseNamespace="urn:http.service.gateway.nss.com")]
        [return: System.Xml.Serialization.SoapElementAttribute("getOrgGatewayFromOrgInetReturn")]
        public string getOrgGatewayFromOrgInet(string agencyCode) {
            object[] results = this.Invoke("getOrgGatewayFromOrgInet", new object[] {
                        agencyCode});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getOrgGatewayFromOrgInetAsync(string agencyCode) {
            this.getOrgGatewayFromOrgInetAsync(agencyCode, null);
        }
        
        /// <remarks/>
        public void getOrgGatewayFromOrgInetAsync(string agencyCode, object userState) {
            if ((this.getOrgGatewayFromOrgInetOperationCompleted == null)) {
                this.getOrgGatewayFromOrgInetOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetOrgGatewayFromOrgInetOperationCompleted);
            }
            this.InvokeAsync("getOrgGatewayFromOrgInet", new object[] {
                        agencyCode}, this.getOrgGatewayFromOrgInetOperationCompleted, userState);
        }
        
        private void OngetOrgGatewayFromOrgInetOperationCompleted(object arg) {
            if ((this.getOrgGatewayFromOrgInetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getOrgGatewayFromOrgInetCompleted(this, new getOrgGatewayFromOrgInetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="urn:http.service.gateway.nss.com", ResponseNamespace="urn:http.service.gateway.nss.com")]
        [return: System.Xml.Serialization.SoapElementAttribute("getOrgInetFromOrgGatewayReturn")]
        public string getOrgInetFromOrgGateway(string codeOrganization) {
            object[] results = this.Invoke("getOrgInetFromOrgGateway", new object[] {
                        codeOrganization});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getOrgInetFromOrgGatewayAsync(string codeOrganization) {
            this.getOrgInetFromOrgGatewayAsync(codeOrganization, null);
        }
        
        /// <remarks/>
        public void getOrgInetFromOrgGatewayAsync(string codeOrganization, object userState) {
            if ((this.getOrgInetFromOrgGatewayOperationCompleted == null)) {
                this.getOrgInetFromOrgGatewayOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetOrgInetFromOrgGatewayOperationCompleted);
            }
            this.InvokeAsync("getOrgInetFromOrgGateway", new object[] {
                        codeOrganization}, this.getOrgInetFromOrgGatewayOperationCompleted, userState);
        }
        
        private void OngetOrgInetFromOrgGatewayOperationCompleted(object arg) {
            if ((this.getOrgInetFromOrgGatewayCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getOrgInetFromOrgGatewayCompleted(this, new getOrgInetFromOrgGatewayCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="urn:http.service.gateway.nss.com", ResponseNamespace="urn:http.service.gateway.nss.com")]
        [return: System.Xml.Serialization.SoapElementAttribute("getOrganizationReturn")]
        public string getOrganization(string orgCode) {
            object[] results = this.Invoke("getOrganization", new object[] {
                        orgCode});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getOrganizationAsync(string orgCode) {
            this.getOrganizationAsync(orgCode, null);
        }
        
        /// <remarks/>
        public void getOrganizationAsync(string orgCode, object userState) {
            if ((this.getOrganizationOperationCompleted == null)) {
                this.getOrganizationOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetOrganizationOperationCompleted);
            }
            this.InvokeAsync("getOrganization", new object[] {
                        orgCode}, this.getOrganizationOperationCompleted, userState);
        }
        
        private void OngetOrganizationOperationCompleted(object arg) {
            if ((this.getOrganizationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getOrganizationCompleted(this, new getOrganizationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="urn:http.service.gateway.nss.com", ResponseNamespace="urn:http.service.gateway.nss.com")]
        [return: System.Xml.Serialization.SoapElementAttribute("getOrganizationsReturn")]
        public string[] getOrganizations(string systemType) {
            object[] results = this.Invoke("getOrganizations", new object[] {
                        systemType});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void getOrganizationsAsync(string systemType) {
            this.getOrganizationsAsync(systemType, null);
        }
        
        /// <remarks/>
        public void getOrganizationsAsync(string systemType, object userState) {
            if ((this.getOrganizationsOperationCompleted == null)) {
                this.getOrganizationsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetOrganizationsOperationCompleted);
            }
            this.InvokeAsync("getOrganizations", new object[] {
                        systemType}, this.getOrganizationsOperationCompleted, userState);
        }
        
        private void OngetOrganizationsOperationCompleted(object arg) {
            if ((this.getOrganizationsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getOrganizationsCompleted(this, new getOrganizationsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="urn:http.service.gateway.nss.com", ResponseNamespace="urn:http.service.gateway.nss.com")]
        [return: System.Xml.Serialization.SoapElementAttribute("getReceivedDocumentCodesReturn")]
        public string[] getReceivedDocumentCodes() {
            object[] results = this.Invoke("getReceivedDocumentCodes", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void getReceivedDocumentCodesAsync() {
            this.getReceivedDocumentCodesAsync(null);
        }
        
        /// <remarks/>
        public void getReceivedDocumentCodesAsync(object userState) {
            if ((this.getReceivedDocumentCodesOperationCompleted == null)) {
                this.getReceivedDocumentCodesOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetReceivedDocumentCodesOperationCompleted);
            }
            this.InvokeAsync("getReceivedDocumentCodes", new object[0], this.getReceivedDocumentCodesOperationCompleted, userState);
        }
        
        private void OngetReceivedDocumentCodesOperationCompleted(object arg) {
            if ((this.getReceivedDocumentCodesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getReceivedDocumentCodesCompleted(this, new getReceivedDocumentCodesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="urn:http.service.gateway.nss.com", ResponseNamespace="urn:http.service.gateway.nss.com")]
        [return: System.Xml.Serialization.SoapElementAttribute("getReceivedMessageIdsByDocumentTypeReturn")]
        public string[] getReceivedMessageIdsByDocumentType(string documentType) {
            object[] results = this.Invoke("getReceivedMessageIdsByDocumentType", new object[] {
                        documentType});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void getReceivedMessageIdsByDocumentTypeAsync(string documentType) {
            this.getReceivedMessageIdsByDocumentTypeAsync(documentType, null);
        }
        
        /// <remarks/>
        public void getReceivedMessageIdsByDocumentTypeAsync(string documentType, object userState) {
            if ((this.getReceivedMessageIdsByDocumentTypeOperationCompleted == null)) {
                this.getReceivedMessageIdsByDocumentTypeOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetReceivedMessageIdsByDocumentTypeOperationCompleted);
            }
            this.InvokeAsync("getReceivedMessageIdsByDocumentType", new object[] {
                        documentType}, this.getReceivedMessageIdsByDocumentTypeOperationCompleted, userState);
        }
        
        private void OngetReceivedMessageIdsByDocumentTypeOperationCompleted(object arg) {
            if ((this.getReceivedMessageIdsByDocumentTypeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getReceivedMessageIdsByDocumentTypeCompleted(this, new getReceivedMessageIdsByDocumentTypeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="urn:http.service.gateway.nss.com", ResponseNamespace="urn:http.service.gateway.nss.com")]
        [return: System.Xml.Serialization.SoapElementAttribute("getReceivedMessageIdsByStartDateEndDateReturn")]
        public string[] getReceivedMessageIdsByStartDateEndDate(long startDateInMilisecond, long endDateInMilisecond) {
            object[] results = this.Invoke("getReceivedMessageIdsByStartDateEndDate", new object[] {
                        startDateInMilisecond,
                        endDateInMilisecond});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void getReceivedMessageIdsByStartDateEndDateAsync(long startDateInMilisecond, long endDateInMilisecond) {
            this.getReceivedMessageIdsByStartDateEndDateAsync(startDateInMilisecond, endDateInMilisecond, null);
        }
        
        /// <remarks/>
        public void getReceivedMessageIdsByStartDateEndDateAsync(long startDateInMilisecond, long endDateInMilisecond, object userState) {
            if ((this.getReceivedMessageIdsByStartDateEndDateOperationCompleted == null)) {
                this.getReceivedMessageIdsByStartDateEndDateOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetReceivedMessageIdsByStartDateEndDateOperationCompleted);
            }
            this.InvokeAsync("getReceivedMessageIdsByStartDateEndDate", new object[] {
                        startDateInMilisecond,
                        endDateInMilisecond}, this.getReceivedMessageIdsByStartDateEndDateOperationCompleted, userState);
        }
        
        private void OngetReceivedMessageIdsByStartDateEndDateOperationCompleted(object arg) {
            if ((this.getReceivedMessageIdsByStartDateEndDateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getReceivedMessageIdsByStartDateEndDateCompleted(this, new getReceivedMessageIdsByStartDateEndDateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="urn:http.service.gateway.nss.com", ResponseNamespace="urn:http.service.gateway.nss.com")]
        [return: System.Xml.Serialization.SoapElementAttribute("getReceivedMessageIdsReturn")]
        public string[] getReceivedMessageIds() {
            object[] results = this.Invoke("getReceivedMessageIds", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void getReceivedMessageIdsAsync() {
            this.getReceivedMessageIdsAsync(null);
        }
        
        /// <remarks/>
        public void getReceivedMessageIdsAsync(object userState) {
            if ((this.getReceivedMessageIdsOperationCompleted == null)) {
                this.getReceivedMessageIdsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetReceivedMessageIdsOperationCompleted);
            }
            this.InvokeAsync("getReceivedMessageIds", new object[0], this.getReceivedMessageIdsOperationCompleted, userState);
        }
        
        private void OngetReceivedMessageIdsOperationCompleted(object arg) {
            if ((this.getReceivedMessageIdsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getReceivedMessageIdsCompleted(this, new getReceivedMessageIdsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="urn:http.service.gateway.nss.com", ResponseNamespace="urn:http.service.gateway.nss.com")]
        [return: System.Xml.Serialization.SoapElementAttribute("getUploadFileURLReturn")]
        public string getUploadFileURL(string ipAddress) {
            object[] results = this.Invoke("getUploadFileURL", new object[] {
                        ipAddress});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getUploadFileURLAsync(string ipAddress) {
            this.getUploadFileURLAsync(ipAddress, null);
        }
        
        /// <remarks/>
        public void getUploadFileURLAsync(string ipAddress, object userState) {
            if ((this.getUploadFileURLOperationCompleted == null)) {
                this.getUploadFileURLOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetUploadFileURLOperationCompleted);
            }
            this.InvokeAsync("getUploadFileURL", new object[] {
                        ipAddress}, this.getUploadFileURLOperationCompleted, userState);
        }
        
        private void OngetUploadFileURLOperationCompleted(object arg) {
            if ((this.getUploadFileURLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getUploadFileURLCompleted(this, new getUploadFileURLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="urn:http.service.gateway.nss.com", ResponseNamespace="urn:http.service.gateway.nss.com")]
        [return: System.Xml.Serialization.SoapElementAttribute("hasReceiverMessageReturn")]
        public string hasReceiverMessage(string msId, string receiverOrgId) {
            object[] results = this.Invoke("hasReceiverMessage", new object[] {
                        msId,
                        receiverOrgId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void hasReceiverMessageAsync(string msId, string receiverOrgId) {
            this.hasReceiverMessageAsync(msId, receiverOrgId, null);
        }
        
        /// <remarks/>
        public void hasReceiverMessageAsync(string msId, string receiverOrgId, object userState) {
            if ((this.hasReceiverMessageOperationCompleted == null)) {
                this.hasReceiverMessageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnhasReceiverMessageOperationCompleted);
            }
            this.InvokeAsync("hasReceiverMessage", new object[] {
                        msId,
                        receiverOrgId}, this.hasReceiverMessageOperationCompleted, userState);
        }
        
        private void OnhasReceiverMessageOperationCompleted(object arg) {
            if ((this.hasReceiverMessageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.hasReceiverMessageCompleted(this, new hasReceiverMessageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="urn:http.service.gateway.nss.com", ResponseNamespace="urn:http.service.gateway.nss.com")]
        [return: System.Xml.Serialization.SoapElementAttribute("sendMessageReturn")]
        public string sendMessage(string xmlMessage) {
            object[] results = this.Invoke("sendMessage", new object[] {
                        xmlMessage});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void sendMessageAsync(string xmlMessage) {
            this.sendMessageAsync(xmlMessage, null);
        }
        
        /// <remarks/>
        public void sendMessageAsync(string xmlMessage, object userState) {
            if ((this.sendMessageOperationCompleted == null)) {
                this.sendMessageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsendMessageOperationCompleted);
            }
            this.InvokeAsync("sendMessage", new object[] {
                        xmlMessage}, this.sendMessageOperationCompleted, userState);
        }
        
        private void OnsendMessageOperationCompleted(object arg) {
            if ((this.sendMessageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sendMessageCompleted(this, new sendMessageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="urn:http.service.gateway.nss.com", ResponseNamespace="urn:http.service.gateway.nss.com")]
        [return: System.Xml.Serialization.SoapElementAttribute("synchronizationAllDepartmentGWReturn")]
        public string[] synchronizationAllDepartmentGW() {
            object[] results = this.Invoke("synchronizationAllDepartmentGW", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void synchronizationAllDepartmentGWAsync() {
            this.synchronizationAllDepartmentGWAsync(null);
        }
        
        /// <remarks/>
        public void synchronizationAllDepartmentGWAsync(object userState) {
            if ((this.synchronizationAllDepartmentGWOperationCompleted == null)) {
                this.synchronizationAllDepartmentGWOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsynchronizationAllDepartmentGWOperationCompleted);
            }
            this.InvokeAsync("synchronizationAllDepartmentGW", new object[0], this.synchronizationAllDepartmentGWOperationCompleted, userState);
        }
        
        private void OnsynchronizationAllDepartmentGWOperationCompleted(object arg) {
            if ((this.synchronizationAllDepartmentGWCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.synchronizationAllDepartmentGWCompleted(this, new synchronizationAllDepartmentGWCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="urn:http.service.gateway.nss.com", ResponseNamespace="urn:http.service.gateway.nss.com")]
        [return: System.Xml.Serialization.SoapElementAttribute("synchronizationDepartmentByCodeOrganizationGWReturn")]
        public string[] synchronizationDepartmentByCodeOrganizationGW(string codeOrganization) {
            object[] results = this.Invoke("synchronizationDepartmentByCodeOrganizationGW", new object[] {
                        codeOrganization});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void synchronizationDepartmentByCodeOrganizationGWAsync(string codeOrganization) {
            this.synchronizationDepartmentByCodeOrganizationGWAsync(codeOrganization, null);
        }
        
        /// <remarks/>
        public void synchronizationDepartmentByCodeOrganizationGWAsync(string codeOrganization, object userState) {
            if ((this.synchronizationDepartmentByCodeOrganizationGWOperationCompleted == null)) {
                this.synchronizationDepartmentByCodeOrganizationGWOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsynchronizationDepartmentByCodeOrganizationGWOperationCompleted);
            }
            this.InvokeAsync("synchronizationDepartmentByCodeOrganizationGW", new object[] {
                        codeOrganization}, this.synchronizationDepartmentByCodeOrganizationGWOperationCompleted, userState);
        }
        
        private void OnsynchronizationDepartmentByCodeOrganizationGWOperationCompleted(object arg) {
            if ((this.synchronizationDepartmentByCodeOrganizationGWCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.synchronizationDepartmentByCodeOrganizationGWCompleted(this, new synchronizationDepartmentByCodeOrganizationGWCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="urn:http.service.gateway.nss.com", ResponseNamespace="urn:http.service.gateway.nss.com")]
        [return: System.Xml.Serialization.SoapElementAttribute("updateErrorMessageReturn")]
        public string updateErrorMessage(string messageId, string errorMessage) {
            object[] results = this.Invoke("updateErrorMessage", new object[] {
                        messageId,
                        errorMessage});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void updateErrorMessageAsync(string messageId, string errorMessage) {
            this.updateErrorMessageAsync(messageId, errorMessage, null);
        }
        
        /// <remarks/>
        public void updateErrorMessageAsync(string messageId, string errorMessage, object userState) {
            if ((this.updateErrorMessageOperationCompleted == null)) {
                this.updateErrorMessageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnupdateErrorMessageOperationCompleted);
            }
            this.InvokeAsync("updateErrorMessage", new object[] {
                        messageId,
                        errorMessage}, this.updateErrorMessageOperationCompleted, userState);
        }
        
        private void OnupdateErrorMessageOperationCompleted(object arg) {
            if ((this.updateErrorMessageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.updateErrorMessageCompleted(this, new updateErrorMessageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="urn:http.service.gateway.nss.com", ResponseNamespace="urn:http.service.gateway.nss.com")]
        [return: System.Xml.Serialization.SoapElementAttribute("updateReceiveFinishReturn")]
        public string updateReceiveFinish(string messageId) {
            object[] results = this.Invoke("updateReceiveFinish", new object[] {
                        messageId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void updateReceiveFinishAsync(string messageId) {
            this.updateReceiveFinishAsync(messageId, null);
        }
        
        /// <remarks/>
        public void updateReceiveFinishAsync(string messageId, object userState) {
            if ((this.updateReceiveFinishOperationCompleted == null)) {
                this.updateReceiveFinishOperationCompleted = new System.Threading.SendOrPostCallback(this.OnupdateReceiveFinishOperationCompleted);
            }
            this.InvokeAsync("updateReceiveFinish", new object[] {
                        messageId}, this.updateReceiveFinishOperationCompleted, userState);
        }
        
        private void OnupdateReceiveFinishOperationCompleted(object arg) {
            if ((this.updateReceiveFinishCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.updateReceiveFinishCompleted(this, new updateReceiveFinishCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void checkReceiverMessageCompletedEventHandler(object sender, checkReceiverMessageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class checkReceiverMessageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal checkReceiverMessageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void getConnectionStatusCompletedEventHandler(object sender, getConnectionStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getConnectionStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getConnectionStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void getDownloadFileURLCompletedEventHandler(object sender, getDownloadFileURLCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getDownloadFileURLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getDownloadFileURLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void getMessageByMessageIdCompletedEventHandler(object sender, getMessageByMessageIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getMessageByMessageIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getMessageByMessageIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void getMessageIdsByPriorityCompletedEventHandler(object sender, getMessageIdsByPriorityCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getMessageIdsByPriorityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getMessageIdsByPriorityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void getMessagePriorityByMessageIdCompletedEventHandler(object sender, getMessagePriorityByMessageIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getMessagePriorityByMessageIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getMessagePriorityByMessageIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void getMessagesCompletedEventHandler(object sender, getMessagesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getMessagesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getMessagesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void getNumberOfReceiveMessageCompletedEventHandler(object sender, getNumberOfReceiveMessageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getNumberOfReceiveMessageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getNumberOfReceiveMessageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void getOrgGatewayFromOrgInetCompletedEventHandler(object sender, getOrgGatewayFromOrgInetCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getOrgGatewayFromOrgInetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getOrgGatewayFromOrgInetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void getOrgInetFromOrgGatewayCompletedEventHandler(object sender, getOrgInetFromOrgGatewayCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getOrgInetFromOrgGatewayCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getOrgInetFromOrgGatewayCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void getOrganizationCompletedEventHandler(object sender, getOrganizationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getOrganizationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getOrganizationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void getOrganizationsCompletedEventHandler(object sender, getOrganizationsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getOrganizationsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getOrganizationsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void getReceivedDocumentCodesCompletedEventHandler(object sender, getReceivedDocumentCodesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getReceivedDocumentCodesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getReceivedDocumentCodesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void getReceivedMessageIdsByDocumentTypeCompletedEventHandler(object sender, getReceivedMessageIdsByDocumentTypeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getReceivedMessageIdsByDocumentTypeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getReceivedMessageIdsByDocumentTypeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void getReceivedMessageIdsByStartDateEndDateCompletedEventHandler(object sender, getReceivedMessageIdsByStartDateEndDateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getReceivedMessageIdsByStartDateEndDateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getReceivedMessageIdsByStartDateEndDateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void getReceivedMessageIdsCompletedEventHandler(object sender, getReceivedMessageIdsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getReceivedMessageIdsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getReceivedMessageIdsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void getUploadFileURLCompletedEventHandler(object sender, getUploadFileURLCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getUploadFileURLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getUploadFileURLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void hasReceiverMessageCompletedEventHandler(object sender, hasReceiverMessageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class hasReceiverMessageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal hasReceiverMessageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void sendMessageCompletedEventHandler(object sender, sendMessageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sendMessageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sendMessageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void synchronizationAllDepartmentGWCompletedEventHandler(object sender, synchronizationAllDepartmentGWCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class synchronizationAllDepartmentGWCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal synchronizationAllDepartmentGWCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void synchronizationDepartmentByCodeOrganizationGWCompletedEventHandler(object sender, synchronizationDepartmentByCodeOrganizationGWCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class synchronizationDepartmentByCodeOrganizationGWCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal synchronizationDepartmentByCodeOrganizationGWCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void updateErrorMessageCompletedEventHandler(object sender, updateErrorMessageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class updateErrorMessageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal updateErrorMessageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void updateReceiveFinishCompletedEventHandler(object sender, updateReceiveFinishCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class updateReceiveFinishCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal updateReceiveFinishCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591